/**

Author: Nikaansh Singh
Last Edited: 9/8/23

This is a short game in which you try and guess a number randomly generated by the computer

1. No global variables. (Global constants are all right.)

2. No strings. Not ever. (You can use cstrings/character arrays, and the cstring and cctype libraries are okay.

3. You should include <iostream>, not stdio. (This applies more to C programmers.) Use new and delete instead of malloc and free

 **/

#include <iostream>
#include <cstdlib>

using namespace std;

int main()
{
  //Making variables
  char yesno = ' ';
  int N = 100;
  int rando = 0;
  int guess = 0;
  bool currentgame = false;
  int numGuess = 0;
  
  cout << "Do you want to play (y or n)?" << endl;
  cin >> yesno;

  //Starts loops that only ends when played writes 'n' after finishing a game
  while (yesno == 'y') {

    //resets number of guesses
    numGuess = 0;

    //sets current game to be true so game can fully start
    if (yesno == 'y') {
      currentgame = true;
    }

    //gets random number
    rando = rand() % N;

    //repeats guessing until current game gets finished
    while (currentgame == true) {

      //trackes number of guesses
      numGuess++;
      
      cout << "What is your guess: " << endl;
      cin >> guess;
      
      if (guess > rando) { //guess too high
	cout << "Too high!" << endl;
      }
      else if (guess < rando) { //guess to low
	cout << "Too low!" << endl;
      }
      else { //guess just right
	currentgame = false;
	cout << "You got the number! It took " << numGuess << ". Do you want to play again (y or n)?" << endl;
	cin >> yesno;
      }
    }
    
  }
  
  return 0;
}
